### DISCUSSION TITLE
How to use stalwart as backend?

### DISCUSSION THREAD

**Discussion by jet10000** [linagora/tmail-flutter#2745] [General]
https://stalw.art/

I have setup a stalwart mail server with jmap server.

How to use tmail client for stalwart mail sever?

<img width="443" alt="image" src="https://github.com/linagora/tmail-flutter/assets/2258120/8456fd07-8c3b-49fb-96a6-965919d288a3">

**Comment by hoangdat** [comment]
It is mobile or web app? If web app, can you show me the error in console. (May be CORS issue)

**Comment by jet10000** [comment]
<img width="1193" alt="image" src="https://github.com/linagora/tmail-flutter/assets/2258120/787f88e0-68e1-4653-9423-3d958767acb8">

**Comment by jet10000** [comment]
stalwart mail server docker-compose.yml file

```
version: '3.3'
services:
  stalwart-mail:
    image: stalwartlabs/mail-server:latest
    container_name: stalwart-mail
    restart: unless-stopped
    ports:
      - "25:25"
#      - "143:143"
#      - "443:443"
#      - "465:465"
      - "587:587"
      - "993:993"
#      - "4190:4190"
      - "8080:8080"
    volumes:
      - ./data:/opt/stalwart-mail
 ```
