### ISSUE TITLE
Load env.file and env.fcm as ENV variables

### ISSUE THREAD

**Issue by ducnm0711** [linagora/tmail-flutter#1965]
# DESC
- Currently in docker-compose and kubernetes, we have to mount file for customize configuration:
```yaml
version: "3"

services:
  tmail-frontend:
    image: linagora/tmail-web:master
    container_name: tmail-frontend
    ports:
      - "8080:80"
    volumes:
      - ./env.file:/usr/share/nginx/html/assets/env.file
```
- I would also want to use ENV vars, this will provide more flexibility and extra security when we deploy in k8s
```yaml
version: "3"

services:
  tmail-frontend:
    image: linagora/tmail-web:master
    container_name: tmail-frontend
    ports:
      - "8080:80"
  environment:
    SERVER_URL : example          #k8s ConfigMap
    ...
    FIREBASE_WEB_API_KEY: secret  #k8s Secret
    ...
```

# DOD
- Able to load env.file and env.fcm from ENV
