### ISSUE TITLE
Support Stallwart

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2302]
## Description

Run TwakeMail using mobile and web app against https://github.com/stalwartlabs/jmap-server

You should be able to produce video demonstrating it works.

## Starting Stallwart

Unzip this:

[stallwart-dir.zip](https://github.com/linagora/tmail-flutter/files/13229870/stallwart-dir.zip)

Then:

```
docker run -d -ti -p 8080:8080 -p 25:25 -p 587:587 -p 465:465  -p 143:143 -p 993:993 -p 4190:4190 -v $PWD/stallwart-dir:/opt/stalwart-mail stalwartlabs/mail-server:latest
```

And once it did start:

```
curl -k -u 'john:12345' https://(container_ip):8080/.well-known/jmap | jq .

{
  "capabilities": {
    "urn:ietf:params:jmap:core": {
      "maxSizeUpload": 50000000,
...
```

**Comment by chibenwa** [comment]
Tried on web. I noticed failures:
 - Stallwart do not answers CORS 
 
```
$ curl -k -XOPTIONS -v https://172.17.0.2:8080/.well-known/jmap 
> OPTIONS /.well-known/jmap HTTP/1.1
> Host: 172.17.0.2:8080
> User-Agent: curl/7.81.0
> Accept: */*
> 
< HTTP/1.1 204 No Content
< date: Wed, 01 Nov 2023 17:21:23 GMT
< 

```

 - My stallwarts uses a self signed certificate that is not recognized by the browser

**Comment by chibenwa** [comment]
I had the idea to proxy the JMAP endpoint through the NGinx container used to serve TMail WEB...

Docker compose:

```
services:
  tmail-frontend:
    image: chibenwa/tmail-web:fix-cyrus
    container_name: tmail-frontend
    ports:
      - "80:80"
    volumes:
      - ./env.file:/usr/share/nginx/html/assets/env.file
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/nginx/fullchain.pem
    networks:
      - tmail
```

nginx.conf:

```
...
    server {
      listen 80;

    location /jmap {
        proxy_pass   https://{stallwart_ip}:8080;
	proxy_ssl_verify                off;
	proxy_ssl_trusted_certificate	/etc/nginx/fullchain.pem;
	proxy_ssl_server_name on;
    }
...
```

And 

```
$ cat env.file 
SERVER_URL=http://127.0.0.1/jmap
...
```

I failed at getting NGinx trust the self signed cert I used for stallwart (boooo) and got 499 errors (then abandonned) but I think getting NGinx to trust the Stallwart certificate we would get something up and running...
